### PR TITLE
Error handling #21

### LINKED ISSUE #21: Error handling
We need to handle errors and provide useful error messages. 

These are the errors I have come across while testing the user registration endpoint and may be of use:

Messages arising from `@Column(nullable = false, unique = true)`
-  java.sql.SQLIntegrityConstraintViolationException: Column 'role' cannot be null
-  java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'vimbayi@mail.com' for key 'user.UK_ob8kqyqqgmefl0aco34akdtpe'

Error message arising from `@NotBlank(message = "Email is a required field")`
- Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] ... [Field error in object 'user' on field 'email': rejected value []; codes [NotBlank.user.email,NotBlank.email,NotBlank.java.lang.String,NotBlank]; arguments: codes [user.email,email]; arguments []; default message [email]]; default message [Email is a required field] ]

### PR DESCRIPTION
**Pull request by Philippevial**
closes #21

I made the decision to change the field annotations i used in pull request #25 and i added error handling relevant to those. 
Instead of using a annotation for a unique email i created a custom exception that is thrown if the new email already is registered.

Also added a few tests for the annotations.

If you have any suggestions on improvements just let me know.

### CODE REVIEW

File: src/main/java/com/example/authservice/entity/User.java [hunk 1]
```diff
@@ -14,9 +15,11 @@ public class User {
     @GeneratedValue(strategy = GenerationType.AUTO)
     private Long id;
 
-    @Column(nullable = false, unique = true)
+    @NotBlank(message = "Email is a required field")
```
Comment (Vimbayinashe) [inline src/main/java/com/example/authservice/entity/User.java]:
```suggestion
    @NotBlank(message = "is a required field")
```
Error message shows a repetitive "_email Email is a required field_" and we could resolve this by removing the name of the field in the error message

Screenshot from 2022-05-13 14-23-04

File: src/main/java/com/example/authservice/entity/User.java [hunk 2]
```diff
@@ -14,9 +15,11 @@ public class User {
...
+    @Email
     private String email;
-    @Column(nullable = false)
+    @NotBlank(message = "Password is a required field")
+    @Size(min = 4, message = "Password must be minimum 4 characters long")
```
Comment (Vimbayinashe) [inline src/main/java/com/example/authservice/entity/User.java]:
```suggestion
    @NotBlank(message = "is a required field")
    @Size(min = 4, message = "must be minimum of 4 characters long")
```

File: src/main/java/com/example/authservice/validator/UniqueEmail.java [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+import java.lang.annotation.*;
+
+@Constraint(validatedBy = UniqueEmailValidator.class)
+@Target(ElementType.FIELD)
+@Retention(RetentionPolicy.RUNTIME)
+public @interface UniqueEmail {
+    String message() default "Email address is already registered";
+    Class<?>[] groups() default { };
+    Class<? extends Payload>[] payload() default { };
+}
```
Comment (Vimbayinashe) [inline src/main/java/com/example/authservice/validator/UniqueEmail.java:14]: Snyggt!

**Comment by Vimbayinashe** [comment]
This looks really great! 

I have one suggestion to remove `debugMessage` field because it is always null

**Review by Vimbayinashe — APPROVED** [review]
